#!/bin/bash

if [[ $(cat /etc/*-release | grep -i "ubuntu") ]]; then
    echo "Ubuntu detected"
    apt-get update
    apt-get install -y wget unzip
    wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    unzip terraform_0.15.5_linux_amd64.zip
    mv terraform /usr/local/bin/
    apt-add-repository --yes --update ppa:ansible/ansible
    apt-get install -y ansible
else
    echo "CentOS detected"
    yum install -y wget unzip
    wget https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    unzip terraform_0.15.5_linux_amd64.zip
    mv terraform /usr/local/bin/
    yum install -y epel-release
    yum install -y ansible
fi
